# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/grocking_simplicity_python',
                'doc_host': 'https://Mees-Molenaar.github.io',
                'git_url': 'https://github.com/Mees-Molenaar/grocking_simplicity_python',
                'lib_path': 'grocking_simplicity_python'},
  'syms': { 'grocking_simplicity_python.core': { 'grocking_simplicity_python.core.foo': ( 'core.html#foo',
                                                                                          'grocking_simplicity_python/core.py'),
                                                 'grocking_simplicity_python.core.say_hello': ( 'core.html#say_hello',
                                                                                                'grocking_simplicity_python/core.py')}}}