# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/grocking_simplicity_python',
                'doc_host': 'https://Mees-Molenaar.github.io',
                'git_url': 'https://github.com/Mees-Molenaar/grocking_simplicity_python',
                'lib_path': 'grocking_simplicity_python'},
  'syms': { 'grocking_simplicity_python.fcopy': { 'grocking_simplicity_python.fcopy.withCopy': ( 'copy.html#withcopy',
                                                                                                 'grocking_simplicity_python/fcopy.py')},
            'grocking_simplicity_python.fdict': { 'grocking_simplicity_python.fdict.dictRemove': ( 'dict.html#dictremove',
                                                                                                   'grocking_simplicity_python/fdict.py'),
                                                  'grocking_simplicity_python.fdict.dictSet': ( 'dict.html#dictset',
                                                                                                'grocking_simplicity_python/fdict.py'),
                                                  'grocking_simplicity_python.fdict.withDictCopy': ( 'dict.html#withdictcopy',
                                                                                                     'grocking_simplicity_python/fdict.py')},
            'grocking_simplicity_python.flist': { 'grocking_simplicity_python.flist.listAppend': ( 'list.html#listappend',
                                                                                                   'grocking_simplicity_python/flist.py')}}}