# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_dict.ipynb.

# %% auto 0
__all__ = ['dictSet', 'dictRemove']

# %% ../00_dict.ipynb 6
def dictSet(
    _dict: Dict,
    key: Any,
    value: Any
) -> Dict:
    new_dict = copy.copy(_dict)  
    new_dict[key] = value
    return new_dict

# %% ../00_dict.ipynb 12
def dictRemove(_dict: Dict,
key: Any) -> Dict:
    copy_dict = copy.copy(_dict)
    del copy_dict[key]
    return copy_dict
