# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_copy.ipynb.

# %% auto 0
__all__ = ['T', 'withCopy']

# %% ../00_copy.ipynb 2
from typing import TypeVar, Callable
import copy

# %% ../00_copy.ipynb 5
T = TypeVar('T')

# %% ../00_copy.ipynb 6
def withCopy(_toCopy: T, modify: Callable) -> T:
    _copy = copy.copy(_toCopy)
    _copy = modify(_copy)
    return _copy
