# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_dict.ipynb.

# %% auto 0
__all__ = ['withDictCopy', 'dictSet', 'dictRemove']

# %% ../01_dict.ipynb 2
from typing import Dict, Any, Callable
import copy

# %% ../01_dict.ipynb 4
def withDictCopy(_dict: Dict, modify: Callable) -> Dict:
    _copy = copy.copy(_dict)
    modify(_copy)
    return _copy

# %% ../01_dict.ipynb 10
def dictSet(
    _dict: Dict,
    key: Any,
    value: Any
) -> Dict:
    new_dict = copy.copy(_dict)  
    new_dict[key] = value
    return new_dict

# %% ../01_dict.ipynb 16
def dictRemove(_dict: Dict,
key: Any) -> Dict:
    copy_dict = copy.copy(_dict)
    del copy_dict[key]
    return copy_dict
