# AUTOGENERATED! DO NOT EDIT! File to edit: ../02_list.ipynb.

# %% auto 0
__all__ = ['listAppend']

# %% ../02_list.ipynb 2
from typing import List, Any
import copy

# %% ../02_list.ipynb 6
def listAppend(
    _list: List,
    item: Any,
) -> List:
    copy_list = copy.copy(_list)
    copy_list.append(item)
    return copy_list
