# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_list.ipynb.

# %% auto 0
__all__ = ['listAppend']

# %% ../01_list.ipynb 6
def listAppend(
    _list: List,
    item: Any,
) -> List:
    copy_list = copy.copy(_list)
    copy_list.append(item)
    return copy_list
